<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>
     net10.0-windows10.0.26100.0
    </TargetFrameworks>

    <UseMaui>true</UseMaui>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- NuGet -->
    <PackageId>DeviceTelemetry.Maui</PackageId>
    <Version>1.1.0</Version>
    <Authors>DaithiBradley</Authors>
    <Description>Cross-platform device telemetry utilities for .NET MAUI</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/DaithiBradley/DeviceTelemetry.Maui</PackageProjectUrl>
    <RepositoryUrl>https://github.com/DaithiBradley/DeviceTelemetry.Maui</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup Condition="$(TargetFramework.StartsWith('net9'))">
    <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.31" />
    <PackageReference Include="System.Management" Version="10.0.2" Condition="$(TargetFramework.Contains('windows'))" />
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework.StartsWith('net10'))">
    <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.90" />
    <PackageReference Include="System.Management" Version="10.0.11" Condition="$(TargetFramework.Contains('windows'))" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>DeviceTelemetry.Maui.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="DeviceTelemetry.Maui.Tests/**" />
    <EmbeddedResource Remove="DeviceTelemetry.Maui.Tests/**" />
    <None Remove="DeviceTelemetry.Maui.Tests/**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
