name: Publish NuGet Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
         dotnet-version: 8.0.x
      
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      
      - name: Add Github NuGet source
        run: dotnet nuget add source --username DaithiBradley --password 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 --store-password-in-clear-text --name github "https://nuget.pkg.github.com/DaithiBradley/index.json" 
        # https://nuget.devexpress.com/VdcHljqcAejewWWyegjgbxywZtQ2KgeBuQGDXqCBlKow4puK6y/api/v3/index.json
        # dotnet nuget add source -n "GitHub" https://nuget.pkg.github.com/DaithiBradley/index.json --api-key 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
        # dotnet nuget push D:\a\BM.DLL\BM.DLL\artifacts\*.nupkg --api-key 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 --source "https://nuget.pkg.github.com/DaithiBradley/index.json" --skip-duplicate
      
      - name: Restore dependencies
        run: dotnet restore
      - name: Build and Publish NuGet Package
        run: |
          dotnet build -c Release
          dotnet pack -c Release -o ./artifacts
        working-directory: ./

      - name: Publish NuGet Package
        run: |
          dotnet nuget push D:\a\DeviceTelemetry.Maui\DeviceTelemetry.Maui\artifacts\*.nupkg --api-key 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 --source "https://nuget.pkg.github.com/DaithiBradley/index.json" --skip-duplicate
        # dotnet nuget push D:\a\BM.DLL\BM.DLL\artifacts\*.nupkg --api-key oy2el6ztpm6zndx4ikyar3blgmd3qpvuhpkekkxjwefv7e --source https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}  # Store your NuGet API key as a GitHub secret



